### PR TITLE
Fix #146 and #147

### LINKED ISSUE #146: [Bug]: ModelInspector - uses incorrect property.QueryIsRedefined
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the uml4net
- [x] I have searched [open](https://github.com/STARIONGROUP/uml4net/issues) and [closed](https://github.com/STARIONGROUP/uml4net/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

The PropertyExtensions.QueryIsRedefined has an incorrect implementation which impacts the ModelInspector

https://github.com/STARIONGROUP/uml4net/blob/e557e5b8b3aefc27fef697341d2dba316d7a958b/uml4net.Extensions/PropertyExtensions.cs#L656

This method needs to be fixed and a new method needs to be added to determine whether a property redefines other properties and also added to the ModelInspector algorithm

```
public static bool QueryIsRedefinition(this IProperty property)

```

### System Configuration

- uml4net version:   
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

### LINKED ISSUE #147: [Feature]: update html reporting to include hyperlink to property that is redefining the current property
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the uml4net
- [x] I have searched [open](https://github.com/STARIONGROUP/uml4net/issues) and [closed](https://github.com/STARIONGROUP/uml4net/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a property has been redefined the following is added to the property table `{redefined}`

Image

however, this does not help navigating to the Class.Property that is redefining the current property. This needs to be added so that a reader of the HTML report can navigate to the Property that is redefining. A similar implementation has already been made for `{subsetted}`

Image

please also add a `{redefinition}` tag for each redefinition including a hyperlink similar to how subsetting is reported on

- [ ] update {redefined} tag - add hyperlink
- [ ] add {redefinition} tags with hyperlink (as many tags as their are redefinitions, similar as for subsetting), see #82 

### System Configuration

- uml4net version:   6.1.1

### PR DESCRIPTION
**Pull request by antoineatstariongroup**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/STARIONGROUP/uml4net/pulls) open
- [x] I have verified that I am following the ReqIFSharp [code style guidelines](https://raw.githubusercontent.com/STARIONGROUP/uml4net/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix #146: Renamed QueryIsRedefined to QueryIsRedefinition and used TryQueryRedefinedByProperty to know if the property has been redefined by another property inside the current class context

Fix #147: Provides link to redefinition and to redefined properties

### CODE REVIEW

File: uml4net.HandleBars/PropertyHelper.cs [hunk 1]
```diff
@@ -286,6 +287,26 @@ public static void RegisterPropertyHelper(this IHandlebars handlebars)
 
                 return property.TryQueryRedefinedByProperty(@class, out _);
             });
+            
+            // Queries whether the Property that redefines the current one
```
Comment (samatstariongroup) [inline uml4net.HandleBars/PropertyHelper.cs]: can you improve a bit this line of documentation, not 100% clear to me

**Review by samatstariongroup — APPROVED** [review]
